#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npx standard --fix
npm run lint
npm run build
#npm run test:coverage
echo "Starting component tests"
npm run cypress:component
echo "Testing complete"