#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npx standard --fix
npm run lint
#npm run test:coverage
echo "Starting tests"
npm run cypress:component
npm run cypress:e2e || true
echo "Testing complete"