#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx standard --fix
yarn lint
#yarn test:coverage
echo "Starting tests"
npm run cypress:component
npm run cypress:e2e || true
echo "Testing complete"